matrix:
  include:
    - language: php
      php:
        - 7.1
      cache:
        directories: src/vendor
      before_script:
        - composer install --dev --prefer-dist
      script:
        - sh bin/build.sh
        - ./src/vendor/bin/phpunit
    - language: node_js
      node_js: 10
      cache: yarn
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      script:
        - yarn lint

notifications:
  email: false
